### ISSUE TITLE
hexo@7 can't use hexo-renderer-typst

### ISSUE THREAD

**Issue by WnagoiYy** [Myriad-Dreamin/typst.ts#583]
**Describe the bug**
hexo@7 can't use hexo-renderer-typst

![A}03G5{AES53F%QN9Q(O7MK](https://github.com/user-attachments/assets/7adbb049-9fbc-45b3-b472-8fb9958cfb5f)
![Z9CABA 9$K551UI$42E6RNR](https://github.com/user-attachments/assets/47aa511e-8901-4aad-b804-6eae70d90c91)

**Comment by Myriad-Dreamin** [comment]
what's the version of node you are using? The running node might be too old to support export syntax.

**Comment by cauphenuny** [comment]
I have a same problem, and I'm using node v18.17.0

**Comment by cauphenuny** [comment]
When I upgrade my node to v22.8.0, the problem still exists.
```
$ hexo -v
INFO  Validating config
ERROR Plugin load failed: hexo-renderer-typst
/Users/ycp/Documents/Blog/data.cauphenuny.github.io/node_modules/.pnpm/hexo-renderer-typst@0.5.0-rc7_@myriaddreamin+typst-ts-node-compiler@0.5.0-rc7_@myriaddreamin+_zhctwcixv6tpnvw5uzbm5z6ote/node_modules/hexo-renderer-typst/index.cjs:9
export const compiler = new Compiler(hexo);
^^^^^^

SyntaxError: Unexpected token 'export'
    at new Script (node:vm:117:7)
    at createScript (node:vm:269:10)
    at runInThisContext (node:vm:317:10)
    at /Users/ycp/Documents/Blog/data.cauphenuny.github.io/node_modules/.pnpm/hexo@6.3.0_chokidar@3.6.0/node_modules/hexo/lib/hexo/index.js:303:18
    at tryCatcher (/Users/ycp/Documents/Blog/data.cauphenuny.github.io/node_modules/.pnpm/bluebird@3.7.2/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/ycp/Documents/Blog/data.cauphenuny.github.io/node_modules/.pnpm/bluebird@3.7.2/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/ycp/Documents/Blog/data.cauphenuny.github.io/node_modules/.pnpm/bluebird@3.7.2/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/ycp/Documents/Blog/data.cauphenuny.github.io/node_modules/.pnpm/bluebird@3.7.2/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/ycp/Documents/Blog/data.cauphenuny.github.io/node_modules/.pnpm/bluebird@3.7.2/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/ycp/Documents/Blog/data.cauphenuny.github.io/node_modules/.pnpm/bluebird@3.7.2/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/ycp/Documents/Blog/data.cauphenuny.github.io/node_modules/.pnpm/bluebird@3.7.2/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/ycp/Documents/Blog/data.cauphenuny.github.io/node_modules/.pnpm/bluebird@3.7.2/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/Users/ycp/Documents/Blog/data.cauphenuny.github.io/node_modules/.pnpm/bluebird@3.7.2/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:491:21)
hexo: 6.3.0
hexo-cli: 4.3.1
os: darwin 23.4.0 14.4

node: 22.8.0
acorn: 8.12.1
ada: 2.9.0
amaro: 0.1.8
ares: 1.33.1
brotli: 1.1.0
cjs_module_lexer: 1.2.2
cldr: 45.0
icu: 75.1
llhttp: 9.2.1
modules: 127
napi: 9
nbytes: 0.1.1
ncrypto: 0.0.1
nghttp2: 1.63.0
nghttp3: 0.7.0
ngtcp2: 1.3.0
openssl: 3.0.13+quic
simdjson: 3.10.0
simdutf: 5.3.4
sqlite: 3.46.1
tz: 2024a
undici: 6.19.8
unicode: 15.1
uv: 1.48.0
uvwasi: 0.0.21
v8: 12.4.254.21-node.19
zlib: 1.3.0.1-motley-71660e1
```

**Comment by WnagoiYy** [comment]
![image](https://github.com/user-attachments/assets/d5c9bf3f-18f5-497c-a857-103388d1ecbe)
@Myriad-Dreamin  v20.14.0
